name: intonize
description: A Flutter app that helps you practice and improve your intonation on your instrument.
publish_to: 'none'
version: 0.0.1+1


environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  syncfusion_flutter_gauges: ^19.3.56
  get:
  pitch_detector_dart: ^0.0.2
  pitchupdart: ^0.0.2
  flutter_audio_capture: ^1.1.0
  flutter_midi: ^1.1.0
  flutter_spinkit: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/Piano.sf2
    - assets/Synth.sf2
    
  fonts:
    - family: Gugi
      fonts:
        - asset: fonts/Gugi-Regular.ttf
